FROM postgres:latest

# Set environment variables for database configuration
ENV POSTGRES_PASSWORD='bannasinmysmoothiemakesittastelikebanana'
ENV POSTGRES_DB='soundcentral'
ENV POSTGRES_USER='pg-laurenhatch'

# Expose the default PostgreSQL port
EXPOSE 5432

CMD ["postgres"]